services:
  - type: web
    name: pdf-capture-form-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DB_PATH
        value: database.db
